### ISSUE TITLE
Accidental Taps

### ISSUE THREAD

**Issue by jboucher614** [pixelfed/mobile-app#126]
Getting accidental taps when scrolling. Occurs when scrolling down, and the lower content hasn't loaded. Scrolling down again over an image is treated as tapping on that image, which opens it in full screen view.

App version 1.0.0.33 (also on lower versions)

Android 13 OneUI 5.1 Samsung S22 Ultra

**Comment by d4f5409d** [comment]
It occurs here too

**Comment by realpixelcode** [comment]
Do you mean the behaviour described in #139, @jboucher614?

**Comment by jboucher614** [comment]
> Do you mean the behaviour described in #139, @jboucher614?

Yes, this is the same issue

**Comment by realpixelcode** [comment]
I just closed #139 as a duplicate.
