### ISSUE TITLE
Scrolling while timeline is loading triggers pinch-to-zoom

### ISSUE THREAD

**Issue by realpixelcode** [pixelfed/mobile-app#139]
When quickly scrolling down in the home timeline, you reach the point where posts are still loading (indicated by the loading spinner).

Now, if you don't react quickly enough (by immediately stopping to scroll) when reaching the loading spinner, then “pinch to zoom” is triggered after a medium delay. (The last image is opened in full-screen.)

Sometimes, pinch-to-zoom is even trigged multiple times at once. That means after going back, the image is re-opened in full-screen, so you have to do the back gesture 3 to 4 more times just to finally get back to the timeline. 

Due to the delay before each pinch-to-zoom, such a minor inattention regularly wastes more than 10 seconds.

This happens to me every 10 to 15 posts in the timeline, i.e. 1 to 2 times per minute, and it's extremely annoying. I have to force myself not to scroll too quickly, just so I'm not interrupted all the time.

OS: Android
App version: 1.0.0.36

**Comment by realpixelcode** [comment]
Might be related to #126.

**Comment by d4f5409d** [comment]
Occurs here

**Comment by realpixelcode** [comment]
Duplicate of #126.
