### ISSUE TITLE
Bug: Swiping logic in posts with multiple images

### ISSUE THREAD

**Issue by MrAn0nym** [pixelfed/mobile-app#14]
You can continue to swipe even though you've reached the last image of a post
https://user-images.githubusercontent.com/63542658/194748206-dcda2fe0-9fe8-42c5-973f-b310b9007800.MOV

**Comment by pabloscloud** [comment]
Can confirm, this is the case. And when swiping back to the first image the dot shows up as 2nd image

**Comment by pabloscloud** [comment]
Can confirm, this is the case. And when swiping back to the first image the dot shows up as 2nd image.

**Comment by pabloscloud** [comment]
Fixed!
