### ISSUE TITLE
[iPadOS] Discover goes blank after brief show

### ISSUE THREAD

**Issue by pgronkievitz** [pixelfed/mobile-app#142]
Hi, just installed an app on my iPad Air 4th gen (iPadOS 17.1) and after tapping Discover button it shows anything briefly and goes blank, nothing is clickable - to do anything with the app you have to „fully” close it and reopen

https://github.com/pixelfed/mobile-app/assets/9089064/619f1386-e049-4964-a822-fcd9122b9093

**Comment by dansup** [comment]
Please update to the latest version, if the issue persists you can reopen this issue.
