### ISSUE TITLE
Alt text added when in edit mode, accepts longer input than alt text in advanced settings

### ISSUE THREAD

**Issue by altshiftzero** [pixelfed/mobile-app#5]
When in edit mode after the photo was made, after the text-button is clicked a pop-up shows for an alt-text input. This input seems to have no length limit. When more than 140 characters are given, this text can be saved. 

If you go to the next step and open advanced settings, you can also edit
The alt text. The full length of the text is shown, but you may only remove characters until the text is 139 characters long, after which it is possible to add a 140th character.

**Comment by dansup** [comment]
Fixed in build 4
