### ISSUE TITLE
Logout after changing app settings

### ISSUE THREAD

**Issue by Medformatik** [pixelfed/mobile-app#53]
I am logged in in the Android app with an account on pixelfed.social.

When I change something in the app settings (e.g. which feeds are displayed) and then save the settings, I get logged out of the app and have to log in again.

**Comment by RustyPixel** [comment]
@PlutoHDDev I am not able reproduce on both a pixel 3aXL and 7pro. 
What are you currently using?

**Comment by PlutoHDDev** [comment]
I am using a Pixel 6 Pro with app version 1.0.0 downloaded from [https://dl.apps.pixelcdn.net/pixelfed-android-beta/pixelfed-android-v1.0.0.0.apk](https://dl.apps.pixelcdn.net/pixelfed-android-beta/pixelfed-android-v1.0.0.0.apk). I just tried it a few more times. The issue does not occur every time, but it does sometimes. I will try to capture it on video later.

**Comment by PlutoHDDev** [comment]
https://user-images.githubusercontent.com/37375186/210213637-dd872de2-5e64-4b36-b831-fe14d1849e45.mp4

**Comment by paulada16** [comment]
Got the same here, but can't login after this error. 
Using the 1.0.0.1 version. 

![Screenshot_20230104-162205](https://user-images.githubusercontent.com/121983243/210661377-146a1803-7c15-4390-ac31-acff0bfc5416.png)

**Comment by PlutoHDDev** [comment]
I think that your issue @paulada16 is a different one. I haven't ever seen the error from your screenshot. I just got logged out and sent back to the login screen as you can see in my video. After that I could simply re-login like normal.

**Comment by paulada16** [comment]
I was changing the same settings, logout, and can't login anymore, showing the box on screenshot. 

Maybe i got two errors simultaneously.

**Comment by PlutoHDDev** [comment]
That is of course possible. My video is from version 1.0.0, maybe something has changed since then, so it's maybe like you described it now. Or two issues occur at the same time.
