### ISSUE TITLE
Manual Log In doesn't work 

### ISSUE THREAD

**Issue by wiewiordev** [pixelfed/mobile-app#58]
In Android app, version 1.0.0.0, I cannot manually log in to my instance, after clicking "Manual Log In" button in modal titled "Can't find my server", the modal dissapears and I can't do anything else in that matter. My instance has the newest version (self-hosted on Yunohost).

**Comment by RustyPixel** [comment]
same as #51

**Comment by wiewiordev** [comment]
Version 1.0.0.1 resolved issue.
