### ISSUE TITLE
Save button in App Settings seems to create a sub instance of the feed page / app

### ISSUE THREAD

**Issue by altshiftzero** [pixelfed/mobile-app#6]
When the save button is pressed, the screenswipe comes from the right instead of the left. When the app is used, you can now always go back to this app settings page from anywhere in the app a swipe from the left is possible.

There is no ability to make this infinite it seems. When you go to the app settings again, a screenswipe is visible from the left as swiping to the previous page.

**Comment by dansup** [comment]
Fixed in build 3!
