### ISSUE TITLE
Network and public feed show all images as “sensitive”

### ISSUE THREAD

**Issue by cjerrington** [pixelfed/mobile-app#7]
I was scrolling through the network and public feeds and saw all images were marked as sensitive. An image I posted showed 
in the feed as well, and have not marked any of the as sensitive. 

![B281E122-FF12-4C65-8BB6-F7BC19093AF7](https://user-images.githubusercontent.com/8809376/194736507-eea63626-9e05-4f06-8a0b-28a4b71e90c5.png)

**Comment by dansup** [comment]
Hi, please navigate to Settings -> App Settings -> and uncheck "Hide feed media"!

**Comment by cjerrington** [comment]
Thanks, maybe a better explanation of what that toggle does would be nice. Makes sense now. Or with the option checked, have a different “sensitive” message up like, “Media hidden, change this in settings”. Better distinction between sensitive and hidden media.
