### ISSUE TITLE
Error loading feed message [Android]

### ISSUE THREAD

**Issue by samolego** [pixelfed/mobile-app#87]
Hi there,

first of, thanks for such a great platform 😊!

I'm getting an issue with feed loading. A popup shows up upon opening the app;

```
Couldn't load feed

An error occured when trying to refresh your feed.

SyntaxError: JSON Parse error: Unexpected token: <
```

![Screenshot_20230119-075330_Pixelfed](https://user-images.githubusercontent.com/34912839/213376069-aed1a6f7-04e4-4e30-b96e-cf7f6f226b53.png)

I'm using the version, advertised here: https://mastodon.social/@pixelfed/109714205686620684

Android version: 13

I can provide logcat as well, if useful.

**Comment by earth-walker** [comment]
Same here on android, only when using an account from pixey.org, I have not tested other instances 
![Screenshot_20230212-173614_Pixelfed](https://user-images.githubusercontent.com/97205490/218341571-557fbaca-b4c4-4ee9-801e-d1fb25b44322.png)

**Comment by samolego** [comment]
Idk if something was changed on the backend, but I downloaded the apk again today and it seems to be fixed now.

**Comment by earth-walker** [comment]
It was certainly not fixed for me, I'm still getting the same error message, only for pixey.org accounts. I tested pxlmo.com and that does not produce this problem. I'm wondering if the problem is with pixey.org's server configuration.

**Comment by sievx** [comment]
I'm getting the same as above. Latest version of Pixelfed app and server. Can upload logs when I'm on PC next.

**Comment by Sidneys1** [comment]
Still getting this exception on most recent apk and server (pixel.infosec.exchange).

Should maybe be reopened?
