### ISSUE TITLE
Not Able to Upload Photos or Videos on pixelfed.social APK 1.0.0.18 using Android 13.0

### ISSUE THREAD

**Issue by Bizzenzxn** [pixelfed/mobile-app#94]
When I click the camera button to upload a photo or video I get a black screen with a blue loading circle, and a button that says 'Go back' that does nothing when I click it. I have to close the app and reopen it to get back to the app's main screen.

![Screenshot_20230310_234603_Pixelfed](https://user-images.githubusercontent.com/43100907/224469824-309b45ec-2a89-438c-a445-228adae61b28.jpg)

**Comment by PierreSelim** [comment]
Same issue here, on Samsung S22:
Android 13
Pixelfed 1.0.018

**Comment by DeadSuperHero** [comment]
Yep, same problem here.

**Comment by zplawecki** [comment]
for me also, I have this issue since first android app was available, now on 1.0.018 it's also present
Xiaomi Mi 11 Ultra, 
Android 13 (previously on 12 also), MIUI 14.0.3 Global
